stages:
  - test
  - build
  - push

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  IMAGE_LATEST: $CI_REGISTRY_IMAGE:latest

# Run tests before building
test:
  stage: test
  image: python:3.13-slim
  services:
    - docker:24-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
  before_script:
    - apt-get update && apt-get install -y docker-compose
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - ./test.sh start
    - ./test.sh test
  after_script:
    - ./test.sh stop
  only:
    - branches
    - tags

# Build Docker image
build:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    - docker info
  script:
    - docker build -t $IMAGE_TAG -t $IMAGE_LATEST .
    - docker save $IMAGE_TAG > image.tar
  artifacts:
    paths:
      - image.tar
    expire_in: 1 hour
  only:
    - branches
    - tags
  needs:
    - test

# Push to registry (only if tests passed)
push:
  stage: push
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker load < image.tar
    - docker push $IMAGE_TAG
    # Push latest tag only for main branch
    - |
      if [ "$CI_COMMIT_REF_NAME" = "main" ]; then
        docker push $IMAGE_LATEST
      fi
    # Push version tags
    - |
      if [ -n "$CI_COMMIT_TAG" ]; then
        docker tag $IMAGE_TAG $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
        docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
      fi
  only:
    - branches
    - tags
  needs:
    - build
  dependencies:
    - build

