{{- if and .Values.ldap.caCert (not .Values.ldap.existingCaCertSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ldap-openfga-sync.fullname" . }}-ca-cert
  labels:
    {{- include "ldap-openfga-sync.labels" . | nindent 4 }}
type: Opaque
stringData:
  ca.crt: {{ .Values.ldap.caCert | quote }}
{{- end }}

