{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ldap-openfga-sync.fullname" . }}
  labels:
    {{- include "ldap-openfga-sync.labels" . | nindent 4 }}
type: Opaque
stringData:
  LDAP_BIND_PASSWORD: {{ .Values.ldap.bindPassword | quote }}
  OPENFGA_STORE_ID: {{ .Values.openfga.storeId | quote }}
  {{- if .Values.openfga.apiToken }}
  OPENFGA_API_TOKEN: {{ .Values.openfga.apiToken | quote }}
  {{- end }}
{{- end }}
